import type { Metadata } from 'next';
import { League_Spartan } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';

const leagueSpartan = League_Spartan({
  weight: ['400', '500', '700'], 
  style: 'normal',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Minesweeper',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${leagueSpartan.className} bg-silver`}>
        <Navbar />
        <main className='flex h-full w-full justify-center min-h-screen'>
          {children}
        </main>
      </body>
    </html>
  );
}
